resources:
  pipelines:
    pipeline_manual_pipeline:
      name: manual_pipeline
      libraries:
        - glob:
            include: ../../src/pipelines/manual_pipeline/transformations/**
      schema: bronze
      continuous: false
      development: false
      photon: true
      channel: CURRENT
      catalog: ${var.catalog_name}
      serverless: true
      root_path: ../../src/pipelines/manual_pipeline
